# unsupervised learning configurations
unsupervised:
  learning_rates:
    auto_encoder_lr: 0.0008
    generator_lr: 0.002
    discriminator_lr: 0.0002
    info_lr: 0.0001 #0.0002
    mode_lr: 0.0008
  model:
    hidden_size: 3000
    encoder_dropout: 0.2
  training:
    use_mutual_info: True
    use_mode_decoder: False
    use_adam_optimization: True
    lambda_z_l2_regularization: 0.1
    lambda_info_loss: 10

# sem-supervised learning configurations
semi_supervised:
  learning_rates:
    auto_encoder_lr: 0.0008
    generator_lr: 0.001
    discriminator_lr: 0.0002
    classifier_lr: 0.001
  model:
    hidden_size: 1000
    encoder_dropout: 0
