# unsupervised learning configurations
unsupervised:
  learning_rates:
    auto_encoder_lr: 0.0001 #0.0008
    generator_lr: 0.001
    discriminator_lr: 0.0002
    info_lr: 0.0002
    mode_lr: 0.0008
  model:
    hidden_size: 1000
    decoder_dropout: 0.25
    encoder_dropout: 0.25
    d_cat_droupout: 0.2
    d_gauss_dropout: 0.2
  training:
    use_mutual_info: True
    use_mode_decoder: True

# sem-supervised learning configurations
semi_supervised:
  learning_rates:
    auto_encoder_lr: 0.0008
    generator_lr: 0.001
    discriminator_lr: 0.0002
    classifier_lr: 0.001
  model:
    hidden_size: 1000
    decoder_dropout: 0.25
    encoder_dropout: 0.25
    d_cat_droupout: 0.2
    d_gauss_dropout: 0.2
